//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawablesGeneratorTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrawablesGeneratorTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkSmall {
            get {
                object obj = ResourceManager.GetObject("DarkSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;animationCustom&quot;: {
        ///		&quot;animatedParts&quot;: {
        ///			&quot;parts&quot;: {
        ///				&quot;butt&quot;: {
        ///					&quot;properties&quot;: {
        ///						&quot;image&quot;: &quot;/assetmissing.png&quot;
        ///					}
        ///				},
        ///				&quot;middle&quot;: {
        ///					&quot;properties&quot;: {
        ///						&quot;image&quot;: &quot;/assetmissing.png&quot;
        ///					}
        ///				},
        ///				&quot;barrel&quot;: {
        ///					&quot;properties&quot;: {
        ///						&quot;image&quot;: &quot;/assetmissing.png&quot;
        ///					}
        ///				}
        ///			}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string Gun {
            get {
                return ResourceManager.GetString("Gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hobo {
            get {
                object obj = ResourceManager.GetObject("hobo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ice {
            get {
                object obj = ResourceManager.GetObject("Ice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightSmall {
            get {
                object obj = ResourceManager.GetObject("LightSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NaturalSmall {
            get {
                object obj = ResourceManager.GetObject("NaturalSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap normal {
            get {
                object obj = ResourceManager.GetObject("normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previewCharSmall {
            get {
                object obj = ResourceManager.GetObject("previewCharSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;animationCustom&quot;: {
        ///		&quot;animatedParts&quot;: {
        ///			&quot;parts&quot;: {
        ///				&quot;blade&quot;: {
        ///					&quot;properties&quot;: {
        ///						&quot;image&quot;: &quot;/assetmissing.png&quot;
        ///					}
        ///				},
        ///				&quot;handle&quot;: {
        ///					&quot;properties&quot;: {
        ///						&quot;image&quot;: &quot;/assetmissing.png&quot;
        ///					}
        ///				}
        ///			}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string Sword {
            get {
                return ResourceManager.GetString("Sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;animationCustom&quot;: {
        ///		&quot;animatedParts&quot;: {
        ///			&quot;parts&quot;: {
        ///				&quot;staff&quot;: {
        ///					&quot;properties&quot;: {
        ///						&quot;image&quot;: &quot;/assetmissing.png&quot;
        ///					}
        ///				},
        ///				&quot;stone&quot;: {
        ///					&quot;properties&quot;: {
        ///						&quot;image&quot;: &quot;/assetmissing.png&quot;
        ///					}
        ///				}
        ///			}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string TeslaStaff {
            get {
                return ResourceManager.GetString("TeslaStaff", resourceCulture);
            }
        }
    }
}
